### PR TITLE
Added isActive() method

### PR DESCRIPTION
**Pull request by Shakarang**
Hello,

As you suggested it, I added an isActive() method.

Have a nice day !

### CODE REVIEW

**Comment by sudeepag** [comment]
Looks good, thanks!

**Comment by Rt19990000** [comment]
Ushehdhd

**Review by Rt19990000 — COMMENTED** [review]
#- Jdjdndnfnf_@****_**_]()

**Comment by Rt19990000** [comment]
Sddd

**Comment by Rt19990000** [comment]
...

**Review by Rt19990000 — COMMENTED** [review]
....

**Pull request merged**
