### PR TITLE
Swift 4 compatibility

### PR DESCRIPTION
**Pull request by asowers1**
🎉

### CODE REVIEW

**Comment by Alberto-Vega** [comment]
Hi @sudeepag I just wanted to ask you if are you considering merging any of this Swift 4 pull requests into master? Cheers

**Review by DIntriglia — APPROVED** [review]

**Comment by rubensantiago** [comment]
@sudeepag can you merge this pull request? :)

**Comment by sudeepag** [comment]
Sorry folks, I've been MIA - merged the PR.

**Comment by rubensantiago** [comment]
Good to have you back! How do we update the Cocoapod? 🤔

**Pull request merged**
